#############################################################################
# JupyterBook settings
# See: https://jupyterbook.org/en/stable/customize/config.html

title     : Data Science in Global Change Ecology # Left navbar
author    : Carl Boettiger
copyright : "2024"  # Goes in the footer
logo      : hex.png # Above title, left navbar
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints"]

# Render content from stored notebooks
execute:
  execute_notebooks: 'off'

# Let's build everything - it takes a bit longer but lets us easily preview
# files that are in draft/progress on the live site, without exposing them
# in the TOC/nav tools.
only_build_toc_files: false

# Enable some myst extensions beyond the default.
parse:
  myst_enable_extensions: 
    - amsmath
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - colon_fence
    - substitution
    - tasklist

# Add links to GitHub repo
# For more info: https://jupyterbook.org/en/stable/basics/repository.html
repository:
  url    : https://github.com/espm-157/website
  branch : main

## Jupyter-Book, not recognized by current theme
html:
  use_repository_button : true
  use_issues_button     : true
  favicon : "_static/favicon.png"
  announcement          : "" # A banner announcement at the top of the site.
  extra_footer: |
        <div class="container color-text-muted" style="margin-top: 1em;">
        <style>
        .icon-2x {
        font-size: 2em;
        margin-right: 1em; /* Add horizontal space between icons */
        }
        </style>
        <a href="https://datahub.berkeley.edu"><i class="fa-solid fa-server icon-2x"></i></a>
        <a href="https://github.com/espm-157"><i class="fa-brands fa-github icon-2x"></i></a>
        <a href="https://espm-157.slack.com/"><i class="fa-brands fa-slack icon-2x"></i></a>
        <span style="float: right;"><img src="_static/img/cc-by.svg"/></span>
        </div>


## shibuya sphinx theme, configure here    
sphinx:
  config:
    project: "ESPM-157"
    html_show_copyright: false
    html_show_sphinx: false
    html_theme: "shibuya"
    templates_path: ["_templates"]
    html_theme_options: {
        "slack_url": "https://espm-157.slack.com", 
        "github_url": "https://github.com/espm-157",
        "nav_links": [
        {
            "title": "Home",
            "url": "index"
        },
    ]
       
    }
    html_context: {
        "source_type": "github",
        "source_user": "espm-157",
        "source_repo": "website",
        "source_version": "main",  # Optional
        "source_docs_path": "/"
        }
    



# Uncomment this later if bibliographic references are desired
# See: https://jupyterbook.org/en/stable/tutorials/references.html

# bibtex_bibfiles:
#   - references.bib
#
# sphinx:
#   config:
#     bibtex_reference_style: author_year
