---
title: "Jetstream Resource Justification for ESPM 157"
author: Carl Boettiger
date: 2017-07-28
output: pdf_document
---

ESPM 157: Data Science for Global Change Ecology introduces upper-division undergraduate students to the fundamentals of data science through applications to major issues in Global Change Ecology, including climate change, fisheries collapse, mass extinctions, and other pressing ecological issues of our time.

Central to the course is a focus on an ability to use computational tools collaboratively and reproducibly.  In this unit, students are introduced to cloud computing both as a way of scaling up computationally intensive tasks, and as a mechanism (and test case) for reproducible, portable, and collaborative analyses.  

The Jetstream cloud platform system, coupled with technologies such as Docker Containers and the RStudio-server Integrated Development Environment enable us to introduce these concepts at the undergraduate level to students with no prior scientific computing experience without ever needing to touch a command shell.  Students can launch their instances and connect to a provisioned docker container running RStudio entirely from the web browser, avoiding the often challenging process of installing a custom research software environment on their own laptop and giving them access to significantly more capable computational resources.  

At this time, we are still experimenting with this approach to determine what strategies and tools are most effective at making this experience seamless and accessible.  The Spring 2016 allocation tested this approach on first-year graduate students without prior scientific computing training with significant success but also some lessons learned.  In extending the allocation I hope to both continue this element to my courses (now in a similarly-structured course aimed at undergraduates) and also refine my approach.

Course Website: <https://espm-157.carlboettiger.info/>
