---
title: "Climate Exercise"
---


# Unit I: Climate Change Module

## Warm-up exercise: Examining CO2 trends in R

- Example from <http://climate.nasa.gov/vital-signs/carbon-dioxide/>
- Raw data from <ftp://aftp.cmdl.noaa.gov/products/trends/co2/co2_mm_mlo.txt>


Which months are the CO2 values at the maximum? Minimum?  Why is this?

What rolling average is used in computing the "trend" line?  How does the trend depend on the rolling average?

------------------------

# Exercise I: Temperature Data

Last year, 2015, has now been confirmed as the warmest year on record.  In this section we will analyze global mean temperature data.

Data from: <http://climate.nasa.gov/vital-signs/global-temperature>

## Question 1:

Describe the data set to the best of your ability given the documentation provided.  Describe what kind of column each data contains and what units it is measured in.  Then address our three key questions in understanding this data:

- How are the measurements made? What is the associated measurement uncertainty?
- What is the resolution of the data?
- Are their missing values? How should they be handled?


## Question 2:

Construct the necessary R code to import and prepare for manipulation the following data set: <http://climate.nasa.gov/system/internal_resources/details/original/647_Global_Temperature_Data_File.txt>


## Question 3:

Plot the trend in global mean temperatures over time.  Describe what you see in the plot and how you interpret the patterns you observe.


## Question 4: Evaluating the evidence for a "Pause" in warming?

The [2013 IPCC Report](https://www.ipcc.ch/pdf/assessment-report/ar5/wg1/WG1AR5_SummaryVolume_FINAL.pdf) included a tentative observation of a "much smaller increasing trend" in global mean temperatures since 1998 than was observed previously.  This led to much discussion in the media about the existence of a "Pause" or "Hiatus" in global warming rates, as well as much research looking into where the extra heat could have gone.  (Examples discussing this question include articles in [The Guardian](http://www.theguardian.com/environment/2015/jun/04/global-warming-hasnt-paused-study-finds), [BBC News](http://www.bbc.com/news/science-environment-28870988), and [Wikipedia](https://en.wikipedia.org/wiki/Global_warming_hiatus)). 

By examining the data here, what evidence do you find or not find for such a pause?  Present an analysis of this data (using the tools & methods we have covered in Foundation course so far) to argue your case.  

What additional analyses or data sources would better help you refine your arguments?

## Question 5: Rolling averages
    
- What is the meaning of "5 year average" vs "annual average"?
- Construct 5 year averages from the annual data.  Construct 10 & 20-year averages. 
- Plot the different averages and describe what differences you see and why.  





# Exercise II: Melting Ice Sheets?

- Data description: <http://climate.nasa.gov/vital-signs/land-ice/>
- Raw data file: <http://climate.nasa.gov/system/internal_resources/details/original/499_GRN_ANT_mass_changes.csv>

## Question 1:

- Describe the data set: what are the columns and units? Where do the numbers come from? 
- What is the uncertainty in measurment? Resolution of the data? Interpretation of missing values?


## Question 2:

Construct the necessary R code to import this data set as a tidy `Table` object.

## Question 3:

Plot the data and describe the trends you observe.



# Exercise III: Rising Sea Levels?

- Data description: <http://climate.nasa.gov/vital-signs/sea-level/>
- Raw data file: <http://climate.nasa.gov/system/internal_resources/details/original/121_Global_Sea_Level_Data_File.txt>


## Question 1:

- Describe the data set: what are the columns and units? 
- Where do these data come from? 
- What is the uncertainty in measurment? Resolution of the data? Interpretation of missing values?


## Question 2:

Construct the necessary R code to import this data set as a tidy `Table` object.

## Question 3:

Plot the data and describe the trends you observe.



# Exercise IV: Arctic Sea Ice?

- <http://nsidc.org/data/G02135>
- <ftp://sidads.colorado.edu/DATASETS/NOAA/G02135/Sep/N_09_area.txt>
    

## Question 1:

- Describe the data set: what are the columns and units? 
- Where do these data come from? 
- What is the uncertainty in measurment? Resolution of the data? Interpretation of missing values?


## Question 2:

Construct the necessary R code to import this data set as a tidy `Table` object.

## Question 3:

Plot the data and describe the trends you observe.    


# Exercise V: Longer term trends in CO2 Records


The data we analyzed in the unit introduction included CO2 records dating back only as far as the measurements at the Manua Loa observatory.  To put these values into geological perspective requires looking back much farther than humans have been monitoring atmosopheric CO2 levels.  To do this, we need another approach.


[Ice core data](http://cdiac.ornl.gov/trends/co2/ice_core_co2.html):

Vostok Core, back to 400,000 yrs before present day 

- Description of data set: <http://cdiac.esd.ornl.gov/trends/co2/vostok.html>
- Data source: <http://cdiac.ornl.gov/ftp/trends/co2/vostok.icecore.co2>

## Questions / Tasks:

- Describe the data set: what are the columns and units? Where do the numbers come from? 
- What is the uncertainty in measurment? Resolution of the data? Interpretation of missing values?
- Read in and prepare data for analysis.
- Reverse the ordering to create a chronological record.  
- Plot data
- Consider various smoothing windowed averages of the data. 
- Join this series to Mauna Loa data
- Plot joined data
- Describe your conclusions



